config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :groups do
  member do
    match 'import_users', to: 'import_users#index', via: [:post, :get]
  end
end

app/models/import_user_to_group.rb
class ImportUserToGroup < Import
  attr_accessor :extname, :original_file, :users_saved, :users_failed

  def call(group)
    @users_saved = []
    @users_failed = []
    read_items do |row, i|
      user = User.where('LOWER(login) = ? ', row[0].to_s.downcase).first
      if user
        unless user.groups.include?(group)
          user.groups << group
        end
        @users_saved<< row[0]
      else
        @users_failed<< "line: #{i}: #{row[0]}"
      end
    end
  end

  def read_items
    i = 0
    read_rows do |row|
      i+= 1
      yield row, i if block_given?
    end
  end

  def is_csv?
    @extname == '.csv'
  end

  def is_xls?
    @extname == '.xls'
  end

  def is_xlsx?
    @extname == '.xlsx'
  end

  def read_rows
    if is_csv?
      csv_options = {:headers => false}
      csv_options[:encoding] = settings['encoding'].to_s.presence || 'UTF-8'
      separator = settings['separator'].to_s
      csv_options[:col_sep] = separator if separator.size == 1
      wrapper = settings['wrapper'].to_s
      csv_options[:quote_char] = wrapper if wrapper.size == 1

      CSV.foreach(filepath, csv_options) do |row|
        yield row if block_given?
      end
    elsif is_xls? || is_xlsx?
      roo_csv = is_xls?  ? Roo::Excel.new(original_file.tempfile) : Roo::Excelx.new(original_file.tempfile)
      sheet = roo_csv.sheet(0)
      sheet.each_with_index do |row, idx|
        yield row if block_given?
      end
    else
      return
    end
  end
end

app/controllers/import_users_controller.rb
class ImportUsersController < ApplicationController
  def index
    @group = Group.find(params[:id])
    if request.post?
      @import = ImportUserToGroup.new
      import_data
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end


  private

  def import_data
    @import.user = User.current
    @import.original_file = params[:file]
    @import.set_default_settings
    @import.file = params[:file]
    @import.extname = File.extname( params[:file].original_filename) if params[:file]
    @import.call(@group)
    flash[:notice] = "#{@import.users_saved.count} users imported. #{@import.users_failed.count} users do not exist: #{@import.users_failed.join('<br/>')}".html_safe
    redirect_to edit_group_path(@group)
  rescue CSV::MalformedCSVError => e
    flash.now[:error] = l(:error_invalid_csv_file_or_settings)
  rescue ArgumentError, EncodingError => e
    flash.now[:error] = l(:error_invalid_file_encoding, :encoding => ERB::Util.h(@import.settings['encoding']))
  rescue SystemCallError => e
    flash.now[:error] = l(:error_can_not_read_import_file)
  end
end

app/helpers/import_users_helper.rb
module ImportUsersHelper
end

app/views/groups/_users.html.erb
<p>
  <%= link_to l(:label_user_new), new_group_users_path(@group), :remote => true, :class => "icon icon-add" %>
  <%= link_to l(:button_import),  import_users_group_path(@group), :class => "icon icon-add" %>
</p>

<% if @group.users.any? %>
  <table class="list users">
    <thead><tr>
      <th><%= l(:label_user) %></th>
      <th style="width:15%"></th>
    </tr></thead>
    <tbody>
    <% @group.users.sort.each do |user| %>
      <tr id="user-<%= user.id %>">
        <td class="name"><%= link_to_user user %></td>
        <td class="buttons">
          <%= delete_link group_user_path(@group, :user_id => user), :remote => true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/import_users/index.html.erb
<h2>Import users</h2>

<%= form_tag(import_users_group_path, :multipart => true) do %>
  <fieldset class="box">
    <legend><%= l(:label_select_file_to_import) %> (CSV)</legend>
    <p>
      <%= file_field_tag 'file' %>
    </p>
  </fieldset>
  <p><%= submit_tag l(:button_import).html_safe, :name => nil %></p>
<% end %>